= Graphite Plugin

== Description

The HiveMQ Graphite plugin allows to publish all Metrics of HiveMQ to your Graphite installation. This plugin collects
internal HiveMQ statistics and also uses custom metrics hooked into HiveMQ with the MetricService of the plugin system.

This Graphite plugin also supports batching, so if you want to have metrics in second resolution in Graphite but don't want
to have the huge network overhead by sending it actually every few seconds, you can batch the send action of the metrics.

== Installation

1. Copy the jar file to your [HIVEMQ_HOME]/plugins folder
2. Copy the graphite-plugin.properties file to your [HIVEMQ_HOME]/conf folder
3. Modify the graphite-plugin.properties file for your Graphite installation
4. Done

== Configuration

The configuration file graphite-plugin.properties can be changed at runtime. It supports the following configuration options:

[cols="1m,1,2" options="header"]
.Configuration Options
|===
|Name
|Default
|Description


|host
|essential, no default value
|The hostname or IP address


|port
|essential, no default value
|The Graphite Port


|batchMode
|false
|whether metrics should be batched


|batchSize
|3
|The number of batches before sending the data


|reportingInterval
|60
|The interval to send metrics


|prefix
|none
|The prefix of all metrics


|===


Furthermore there is the option to use environment variables to configure the plugin.
They correspond to the options set in the graphite-plugin.properties file. A configuration set in an environment variable will take precedence over a configuration set in the properties file.


[cols="1m,2" options="header"]
.Configuration with Environment Variables Options
|===
|Environment Variable
|Description


|HIVEMQ_GRAPHITE_HOST
|The hostname or IP address

|HIVEMQ_GRAPHITE_PORT
|The Graphite Port


|HIVEMQ_GRAPHITE_BATCH_MODE
|whether metrics should be batched


|HIVEMQ_GRAPHITE_BATCH_SIZE
|The number of batches before sending the data


|HIVEMQ_GRAPHITE_REPORTING_INTERVAL
|The interval to send metrics


|HIVEMQ_GRAPHITE_PREFIX
|The prefix of all metrics

|===


== Example configuration file
----
host = localhost

port = 2003

batchMode = false

batchSize = 3

reportingInterval = 60

prefix =
----